### ISSUE TITLE
Change location and style of zoom control.

### ISSUE THREAD

**Issue by dbrnz** [dbrnz/flatmap-mvt-viewer#14]
Use (+) and (-) icon from styleguide. (zoom in and zoom out icon). please refer to Zeplin for
icon location of the flatmap -- https://zpl.io/ad58lR7

**Comment by dbrnz** [comment]
Fixed with release 0.9.5.

The position of this control can now be specified by passing it either as an option when creating a `MapManager`, which set the default for all maps, or to `loadMap()` (for a particular map):
```
{
    navigationControl: true
}
```
will position the control in its default `bottom-right` position, whereas:
```
{
    navigationControl: 'top-right'
}
```
will place it at the top right.

The controls can be styled using CSS -- the relevant HTML is:
```
<button class="mapboxgl-ctrl-zoom-in" type="button" title="Zoom in" aria-label="Zoom in">
    <span class="mapboxgl-ctrl-icon" aria-hidden="true"></span>
</button>
<button class="mapboxgl-ctrl-zoom-out" type="button" title="Zoom out" aria-label="Zoom out">
    <span class="mapboxgl-ctrl-icon" aria-hidden="true"></span>
</button>
```

**Comment by dbrnz** [comment]
@alan-wu, could you please get me PNGs for the zoom +/- buttons in the same style as the reset button of issue #21. I will then bundle them with the map viewer. Thanks.

**Comment by alan-wu** [comment]
Sure, give me a bit of time, I will also give you a set for the hover over icon.

**Comment by alan-wu** [comment]
![new_zoomin](https://user-images.githubusercontent.com/1332423/80779169-ec233980-8bbe-11ea-9398-1e12d749e1bf.png)
![new_zoomin_selected](https://user-images.githubusercontent.com/1332423/80779172-ecbbd000-8bbe-11ea-9e37-0dada3a86a15.png)
![new_zoomout](https://user-images.githubusercontent.com/1332423/80779173-edecfd00-8bbe-11ea-8717-ca39cdab9fc8.png)
![new_zoomout_selected](https://user-images.githubusercontent.com/1332423/80779174-edecfd00-8bbe-11ea-94bd-6967f43df6e1.png)

**Comment by dbrnz** [comment]
New button icons in release @dbrnz/flatmap-viewer@0.9.7.
