### ISSUE TITLE
Change font and background of labels.

### ISSUE THREAD

**Issue by dbrnz** [dbrnz/flatmap-mvt-viewer#16]
This needs a PNG of the label background so that `stretch` areas can be defined.

**Comment by dbrnz** [comment]
@uxdesigndept, would you please upload the PNG images as part of a comment to this issue. I know you provided them in Asana (or was it Slack?) but I now cannot find where they are in about three or four different message threads. Thanks.

**Comment by dbrnz** [comment]
@uxdesigndept  you made a request to use 14pt Helvetica for the labels. That font is not available in the OpenMapTiles font stack that the flatmaps use. The available fonts are:
* Noto Sans (as patched by Klokan Technologies)
* Open Sans
* PT Sans
* Roboto
* Metropolis

See [here](https://github.com/openmaptiles/fonts) for details.

Failing them, we could use ESRI's OpenStreetMap font stack. The fonts available in it are:
* Avenir Next LT Pro Demi
* Avenir Next LT Pro Regular
* Architects Daughter Regular
* Arial Unicode MS Regular
* Arial Unicode MS Bold
* Noto Sans Bold
* Noto Sans Italic
* Noto Sans Regular

Another font stack we could use is at https://glfonts.lukasmartinelli.ch/ although for longevity I would prefer we use a font stack hosted by a major organisation.

Which of the above fonts would you like to use instead of Helvetica?

**Comment by dbrnz** [comment]
> @uxdesigndept, would you please upload the PNG images as part of a comment to this issue. I know you provided them in Asana (or was it Slack?) but I now cannot find where they are in about three or four different message threads. Thanks.

The images are:

![label-inactive-white](https://user-images.githubusercontent.com/239220/79549828-985b1f80-80eb-11ea-84bc-e84927de0e07.png)

![label-active-purple](https://user-images.githubusercontent.com/239220/79549844-9db86a00-80eb-11ea-8a5b-0639b55021be.png)

**Comment by dbrnz** [comment]
Two different backgrounds have been given for feature labels, one an `active` feature, the other for an `inactive` feature. @alan-wu and @uxdesigndept, what determines whether a feature is active or inactive? How is the state of a feature changed?

**Comment by dbrnz** [comment]
Mapbox does not support changing label backgrounds using a feature's state, hence only the `active` background has been implemented, although the label's text changes to white (from black) when the label is active.

**Comment by alan-wu** [comment]
Hi Dave, thanks for the update. I dont think having the purple background and and black font looks good.
Can I suggest the following change please?
Inactive: white background, black text  and
Active: white background, purple text.

By the way, allowing more space on the sides should look better.
Please see https://app.zeplin.io/project/5e9e32490830897c933f27c5/screen/5e9d01ac4789ba53b36a8cbc

**Comment by dbrnz** [comment]
Will do @alan-wu. Also see issue #19.

**Comment by dbrnz** [comment]
Desired padding:

<img width="343" alt="Screen Shot 2020-04-23 at 10 23 58 AM" src="https://user-images.githubusercontent.com/239220/80039787-b4781a00-854c-11ea-9209-f01acac2ff4d.png">

**Comment by dbrnz** [comment]
@alan-wu are you able to get me a PNG of a minimal width/height rounded rectangle with shadow that is the label background, against a **transparent** background? (i.e. there's transparency outside the corners, not the white that a screenshot gives). Thanks.

**Comment by alan-wu** [comment]
![bg_white](https://user-images.githubusercontent.com/1332423/80045575-f3fa3280-855b-11ea-8e83-a3140cdee517.png)

**Comment by dbrnz** [comment]
Is this the minimum size a label background should be? i.e. Would a short label have this size background? What I'm after is a minimum width/height background, for say a 1-character label with padding. This background then stretches to fit content.

**Comment by alan-wu** [comment]
Try this one... about 20px padding on each side and 7px for that 1-character width. It really depends on the  font size however.
![minimal](https://user-images.githubusercontent.com/1332423/80154347-7bef4380-8613-11ea-850c-7d3a3eb30d6c.png)

**Comment by dbrnz** [comment]
This gives the following? I'm not sure about the corners though.

<img width="192" alt="Screen Shot 2020-04-24 at 11 11 29 AM" src="https://user-images.githubusercontent.com/239220/80158454-a1347f80-861c-11ea-8373-f1636ddeb344.png">

**Comment by alan-wu** [comment]
Is the first one I sent ok? The resizing may have removed the transparency

**Comment by alan-wu** [comment]
Yes, the resizing remove it, I will send another one through

**Comment by alan-wu** [comment]
![big_minimal](https://user-images.githubusercontent.com/1332423/80161841-c1b50780-8625-11ea-9289-faa717dbe1fe.png)
Try this

**Comment by dbrnz** [comment]
But that doesn't have a minimal width. Anyway I've just published `@dbrnz/flatmap-viewer@0.9.6` (which uses purple/black text for labels) and provided details of how to specify images in #19, so you can now test/try things to find what works.

**Comment by alan-wu** [comment]
Thanks, just cheked. The export from gimp didnt export the resized (minimal) one.
