### ISSUE TITLE
Compilation error v0.4.0

### ISSUE THREAD

**Issue by alan-wu** [dbrnz/flatmap-mvt-viewer#2]
I received the following error when build with webpack

ERROR in ./src/flatmaps/src/interactions.js 155:12
Module parse failed: 'return' outside of function (155:12)
You may need an appropriate loader to handle this file type.
|     {
|         if (this._modal) {
>             return;
|         }
| 
 @ ./src/flatmaps/src/flatmap.js 31:0-51 232:37-53
 @ ./src/flatmapsDialog.js
 @ ./src/index.js

and the following error when compiling with parcel

/home/alan/git_repos/flatmap-mvt-viewer/src/interactions.js:252:0: Unexpected token (252:0)
  250 |     }
  251 | 
> 252 | }
  253 | 
  254 | //==============================================================================
  255 |

**Comment by dbrnz** [comment]
Fixed with commit 79ac1fa.
