### ISSUE TITLE
Enable reset icon with navigationControl flag

### ISSUE THREAD

**Issue by alan-wu** [dbrnz/flatmap-mvt-viewer#21]
It will be nice to be able to reset to the initial position and zoom level with a single button and preferably look similar to the following image.

![mapReset](https://user-images.githubusercontent.com/1332423/80689117-ed9e2480-8b20-11ea-9c44-207178333d58.png)

**Comment by alan-wu** [comment]
![new_reset](https://user-images.githubusercontent.com/1332423/80779184-f5140b00-8bbe-11ea-9c59-fba9b2dcae2e.png)
![new_reset_selected](https://user-images.githubusercontent.com/1332423/80779186-f5aca180-8bbe-11ea-9b91-417de0eee413.png)

**Comment by dbrnz** [comment]
In release @dbrnz/flatmap-viewer@0.9.7.
