### ISSUE TITLE
Incorrect minimap bound

### ISSUE THREAD

**Issue by alan-wu** [dbrnz/flatmap-mvt-viewer#29]
Hi, the minimap works well but I notice an issue with it if a flatmap state is set before the minimap is initialised. 

```
        let promise1 = this.mapManager.loadMap(
            ...          
            minimap: minimap
          });
        promise1.then(returnedObject => {
          this.mapImp.setState(_stateToBeSet);
        })
```
The above codes cause the minimap to be initialised with the newly set bound as I suspect the minimap uses the current bound of the actual display on the [onAdd event](https://github.com/ABI-Software/flatmap-viewer/blob/c781f7fc64592218fbcc40d6e3d08022e056bf32/src/minimap.js#L152).

Thanks.

**Comment by dbrnz** [comment]
Fixed with commit fba3bc7.
