### ISSUE TITLE
Add the ability to enable and disable Pan/Zoom events.

### ISSUE THREAD

**Issue by alan-wu** [dbrnz/flatmap-mvt-viewer#32]
Is there anyway to disable/enable pan and zoom event?
Not high priority.

**Comment by dbrnz** [comment]
At the moment you always get pan/zoom events but being able to turn them on and off is a good idea. Simple to do -- it will go into the next release.

**Comment by dbrnz** [comment]
Implemented in @abi-software/flatmap-viewer@2.2.0-beta.6
